# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_converter:
        enabled: false
    body_listener: true
    format_listener:
        enabled: true
        rules:
            - { path: '^/', host: 'api.*', priorities: [ 'json', 'xml' ] , fallback_format: json, prefer_extension: false }
            - { path: '^/', priorities: [ 'json' ], fallback_format: json, prefer_extension: false }