# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        attendee:
            persistence:
                # the driver can be orm, mongodb or phpcr
                driver: orm
                model: App\Domain\Entity\Attendee
                provider: ~
                finder: ~
            properties:
                name: ~
                nickName: ~
                orderCode: ~
                email: ~
