version: '3.8'
services:
    php:
        image: ghcr.io/bakerware/docker-images/php-8.1-dev:latest
        restart: always
        volumes:
            - './:/usr/src/app'
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal
        networks:
            - web
        extra_hosts:
            - 'host.docker.internal:host-gateway'
    nginx:
        image: nginx:1.21-alpine
        restart: always
        volumes:
            - './:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        depends_on:
            - php
        links:
            - php
        networks:
            - web
        labels:
            - "traefik.enable=true"
            - "traefik.http.middlewares.pch-service-redirect-to-https.redirectscheme.scheme=https"
            - "traefik.http.routers.pch-service.rule=HostRegexp(`pch-service.bw-dev.nl`)"
            - "traefik.http.routers.pch-service.middlewares=pch-service-redirect-to-https@docker"
            - "traefik.http.routers.pch-service.entrypoints=web"
            - "traefik.http.routers.pch-service-secure.rule=HostRegexp(`pch-service.bw-dev.nl`)"
            - "traefik.http.routers.pch-service-secure.entrypoints=websecure"
            - "traefik.http.routers.pch-service-secure.tls.domains[0].main=pch-service.bw-dev.nl"
networks:
    web:
        external: true
