api.attendee.me:
  path: /attendee/me
  controller: App\Controller\AttendeeController::me
  methods: GET

api.attendee.find:
  path: /attendee/{identifier}
  controller: App\Controller\AttendeeController::find
  methods: GET

api.attendee.list:
  path: /attendee
  controller: App\Controller\AttendeeController::listAttendees
  methods: GET

api.attendee.image:
  path: /attendee/{attendee}/image
  controller: App\Controller\AttendeeController::getAttendeeImage
  methods: GET

api.attendee.update:
  path: /attendee/{attendee}
  controller: App\Controller\AttendeeController::updateAttendee
  methods: PUT

api.attendee.update_roles:
  path: /attendee/{attendee}/roles
  controller: App\Controller\AttendeeController::setAttendeeRoles
  methods: PUT

api.attendee.set-password:
  path: /attendee/me/password
  controller: App\Controller\AttendeeController::updatePassword
  methods: PUT