api.attendee.me:
    path: /attendee/me
    controller: App\Controller\AttendeeController::me
    methods: GET

api.attendee.image:
    path: /attendee/{attendee}/image
    controller: App\Controller\AttendeeController::getAttendeeImage
    methods: GET
