api.team.all:
  path: /team
  controller: App\Controller\TeamController::all
  methods: GET

api.team.create:
  path: /team
  controller: App\Controller\TeamController::createTeam
  methods: POST

api.team.update:
  path: /team/{team}
  controller: App\Controller\TeamController::updateTeam
  methods: PUT